// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elwpepbtcshbbysnbzsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd3BlcGJ0Y3NoYmJ5c25ienNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzQ2ODYsImV4cCI6MjA2NzIxMDY4Nn0.2eqc8HJcqesJsTE0KfTTMG1DV4Qx83ysbLy9GLbKoBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});